import re
from typing import Generator, Callable

def generator_numbers(text: str) -> Generator[float, None, None]:
    '''Returns a generator that generates numbers from the input text.'''
    pattern = r"\s(-?\d+(\.\d+)?)\s" # Regular expression to match Real numbers.

    for match in re.finditer(pattern, " " + text + " "): # Add spaces to the beginning and end of the text to match the first and last numbers.
        yield float(match.group(1)) # Convert the matched number to a float and return it.
        

def sum_profit(text: str, func: Callable) -> float:
    '''Returns the sum of the numbers generated by the input function.'''
    return sum(func(text))

text = "Загальний дохід працівника складається з декількох частин: 1000.01 як основний дохід, доповнений додатковими надходженнями 27.45 і 324.00 доларів."
total_income = sum_profit(text, generator_numbers)
print(f"Загальний дохід: {total_income}")